#!/bin/sh

cd -P `dirname "$0"` >/dev/null 2>&1

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib/native/`uname -m`
export PYTHONPATH=$PWD/app:$PWD/lib
export XDG_DATA_DIRS=$PWD/resources:$XDG_DATA_DIRS

cd - >/dev/null 2>&1

exec python -OO -m solaar "$@"
#exec python -OO -m profile -o $TMPDIR/profile.log app/solaar.py "$@"
