#!/usr/bin/env python
# -*- python-mode -*-
"""Takes care of starting the main function."""

from __future__ import absolute_import

import sys


def solaar_init():
	import os.path as _path

	prefix = _path.dirname(_path.dirname(_path.realpath(_path.abspath(__file__))))

	dist_lib = _path.join(prefix, 'share', 'solaar', 'lib')
	src_lib = _path.join(prefix, 'src')

	for location in (dist_lib, src_lib):
		init_py = _path.join(location, 'hidapi', '__init__.py')
		if _path.exists(init_py):
			sys.path.insert(1, location)
			break


if __name__ == '__main__':
	if sys.version_info >= (2, 8):
		sys.exit("Python 3 is not supported by hidconsole.")

	solaar_init()
	from hidapi import hidconsole
	hidconsole.main()
