#!/bin/sh

cd -P `dirname "$0"`/.. >/dev/null 2>&1

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib/native/`uname -m`
export PYTHONPATH=$PWD/lib

cd - >/dev/null 2>&1

exec python -OO -m logitech.ur_scanner "$@"
